// Fixed categories for the grocery list (Aldi-style walk-through order).
// Keywords are generous to catch as many free-text mentions as possible.
// Matches are case-insensitive substring matches on the item name.

export const CATEGORIES = [
  {
    id: 'produce',
    name: 'Obst & Gemüse',
    emoji: '🥬',
    keywords: [
      'apfel','äpfel','birne','birnen','banane','bananen','trauben','traube',
      'erdbeer','erdbeeren','himbeer','himbeeren','blaubeer','blaubeeren','beere','beeren',
      'kirsche','kirschen','pflaume','pflaumen','mango','mangos','ananas','papaya','kiwi',
      'orange','orangen','zitrone','zitronen','limette','limetten','grapefruit',
      'melone','wassermelone','honigmelone','pfirsich','nektarine','aprikose',
      'tomate','tomaten','gurke','gurken','paprika','zucchini','aubergine','auberginen',
      'kartoffel','kartoffeln','süßkartoffel','möhre','möhren','karotte','karotten',
      'zwiebel','zwiebeln','schalotte','knoblauch','lauch','porree','sellerie','fenchel',
      'salat','kopfsalat','eisberg','feldsalat','rucola','rauke','spinat','mangold',
      'brokkoli','blumenkohl','kohl','rotkohl','weißkohl','spitzkohl','wirsing','grünkohl',
      'rosenkohl','kohlrabi','rote bete','radieschen','rettich','pastinake',
      'kürbis','hokkaido','butternut','champignon','champignons','pilz','pilze','shiitake',
      'kräuter','petersilie','schnittlauch','basilikum','dill','koriander','thymian frisch',
      'rosmarin frisch','minze','oregano frisch','ingwer','kurkuma frisch',
      'avocado','avocados','oliven frisch','feige','feigen','granatapfel',
    ],
  },
  {
    id: 'bakery',
    name: 'Bäckerei & Brot',
    emoji: '🥖',
    keywords: [
      'brot','brötchen','semmel','schrippe','wecken','vollkornbrot','graubrot','mischbrot',
      'roggenbrot','dinkelbrot','toast','toastbrot','sandwichbrot','baguette','ciabatta',
      'focaccia','fladenbrot','pita','naan','laugenstange','laugenbrezel','brezel','breze',
      'croissant','pain au chocolat','kuchen','muffin','muffins','donut','berliner','krapfen',
      'zopf','hefezopf','streuselkuchen','rührkuchen','biskuit','kekse','cookies-frisch',
      'knäckebrot','zwieback','pumpernickel',
    ],
  },
  {
    id: 'fish',
    name: 'Fisch & Meeresfrüchte',
    emoji: '🐟',
    keywords: [
      'fisch','lachs','räucherlachs','graved lachs','thunfisch-frisch','forelle','räucherforelle',
      'makrele','räuchermakrele','hering','matjes','rollmops','sardine','sardinen-frisch',
      'sardelle','sardellen-frisch','kabeljau','seelachs','pollack','dorsch','scholle',
      'seezunge','seeteufel','rotbarsch','zander','wolfsbarsch','doraden','dorade',
      'garnele','garnelen','shrimp','shrimps','krabbe','krabben','hummer','languste',
      'tintenfisch','calamari','octopus','oktopus','muscheln','miesmuscheln','jakobsmuscheln',
      'austern','meeresfrüchte','fischfilet','sushi','sashimi','nigiri','maki',
    ],
  },
  {
    id: 'protein',
    name: 'Protein',
    emoji: '🥩',
    keywords: [
      // Pflanzlich
      'tofu','räuchertofu','seidentofu','naturtofu','tempeh','seitan','lupinen','lupinenschnetzel',
      'sojaschnetzel','sojahack','sojagranulat','veganes hack','veganer hack','vegan hack',
      'vegan-hack','pflanzenhack','beyond','beyond meat','beyond burger','incredible burger',
      'veggie burger','veggie-burger','gemüseburger','linsenburger','linsenpatties',
      'kichererbsenpatties','falafel','falafelbällchen','bratlinge','gemüsebratlinge',
      'hummus','humus','edamame','sojaschnitzel','vegane schnitzel','vegane würstchen',
      'vegane wurst','vegane salami','vegane bolognese','sojacreme','proteinpulver',
      'proteindrink','proteinmilch','erbsenprotein','hafer-protein',
      // Tierisch — Rind/Schwein/Geflügel/Lamm
      'hack','hackfleisch','gehacktes','rinderhack','schweinehack','gemischtes hack',
      'steak','rindersteak','hüftsteak','rumpsteak','entrecote','filet','rinderfilet',
      'schweinefilet','schnitzel','wiener schnitzel','hähnchen','hähnchenbrust','hähnchenschenkel',
      'pute','putenbrust','putenschnitzel','huhn','hühnchen','hühnerbrust','ente','entenbrust',
      'lamm','lammkeule','lammkotelett','lammfilet','kotelett','koteletts','rippchen',
      'braten','sauerbraten','schweinebraten','rinderbraten','gulasch','rindergulasch',
      // Wurstwaren
      'bratwurst','bratwürste','grillwurst','weißwurst','bockwurst','wiener','frankfurter',
      'thüringer','knacker','salami-frisch','salamistange','mettwurst','mett','hackepeter',
      'leberkäse','fleischkäse','speck','bacon','schinkenspeck','pancetta','chorizo',
      'merguez','kabanossi',
      // Eier
      'eier','ei','freilandeier','bodenhaltung','bio-eier','bioeier','wachteleier',
      'eiweiß','eigelb','flüssigei',
    ],
  },
  {
    id: 'dairy',
    name: 'Milchprodukte pflanzlich & Milch',
    emoji: '🥛',
    keywords: [
      'milch','vollmilch','haltbare milch','h-milch','laktosefrei','laktosefreie milch',
      'hafermilch','haferdrink','sojadrink','sojamilch','mandelmilch','reisdrink','reismilch',
      'kokosmilch','kokosdrink','erbsendrink','cashewdrink','haselnussdrink',
      'sahne','schlagsahne','sprühsahne','kochsahne','hafer-sahne','soja-sahne','hafersahne',
      'kondensmilch','buttermilch','kefir','ayran',
      'joghurt','naturjoghurt','griechischer joghurt','skyr','sojajoghurt','kokosjoghurt',
      'haferjoghurt','pflanzenjoghurt','quark','magerquark','speisequark','sojaquark',
      'schmand','crème fraîche','creme fraiche','crème','sauerrahm',
      'frischkäse','sojafrischkäse','hüttenkäse','cottage cheese',
      'butter','pflanzenbutter','margarine','sojabutter','mandelbutter-brot',
      'pudding','milchreis','grießbrei','vanillesoße',
    ],
  },
  {
    id: 'cheese',
    name: 'Käse & Aufschnitt',
    emoji: '🧀',
    keywords: [
      'käse','hartkäse','gouda','edamer','emmentaler','bergkäse','parmesan','grana padano',
      'pecorino','mozzarella','büffelmozzarella','burrata','feta','hirtenkäse','schafskäse',
      'halloumi','grillkäse','camembert','brie','blauschimmel','gorgonzola','roquefort',
      'ricotta','mascarpone','raclettekäse','raclette','käsescheiben','reibekäse','pizzakäse',
      'veganer käse','cashewkäse','soja-käse','pflanzenkäse','vegane scheiben',
      'aufschnitt','wurstaufschnitt','schinken','kochschinken','hinterkochschinken',
      'rohschinken','parma','serrano','prosciutto','lachsschinken','putenbrust-aufschnitt',
      'hähnchenbrust-aufschnitt','geflügelwurst','salami-aufschnitt','salami','mortadella',
      'fleischwurst','lyoner','leberwurst','teewurst','bierwurst','cervelat',
      'vegane wurst-scheiben','veganer aufschnitt','veggie-aufschnitt',
    ],
  },
  {
    id: 'frozen',
    name: 'Tiefkühl',
    emoji: '❄️',
    keywords: [
      'tk','tk-','tiefkühl','tiefgefroren','gefroren','gefrier','tkgemüse','tk-gemüse',
      'tk-beeren','tk-obst','tk-pizza','tk-pommes','tk-lachs','tk-fisch','fischstäbchen',
      'pizza','tiefkühlpizza','pommes','pommes frites','kroketten','rösti','hash browns',
      'eis','speiseeis','eiscreme','magnum','cornetto','vanilleeis','schokoladeneis',
      'sorbet','fruchteis','wassereis','eiswürfel',
      'lasagne-tk','spinat tk','erbsen tk','spinattaler',
    ],
  },
  {
    id: 'dry',
    name: 'Trockenwaren & Backen',
    emoji: '🌾',
    keywords: [
      'mehl','dinkelmehl','vollkornmehl','weizenmehl','roggenmehl','buchweizenmehl',
      'kichererbsenmehl','mandelmehl','kokosmehl','glutenfrei','glutenfreies mehl',
      'zucker','rohrzucker','brauner zucker','puderzucker','vanillezucker','gelierzucker',
      'süßstoff','stevia','erythrit','xylit','agavendicksaft','ahornsirup','reissirup',
      'reis','basmati','basmatireis','jasminreis','milchreis','naturreis','vollkornreis',
      'wildreis','risotto','risottoreis','arborio','parboiled',
      'nudeln','pasta','spaghetti','linguine','tagliatelle','penne','rigatoni','fusilli',
      'farfalle','makkaroni','maccheroni','rotini','conchiglie','orecchiette','gnocchi',
      'tortellini','ravioli','lasagneblätter','cannelloni','couscous','bulgur','quinoa',
      'hirse','amaranth','graupen','gerstengraupen','grünkern','hafer','haferkleie',
      'haferflocken','kernige flocken','zarte flocken','porridge','müsli','granola',
      'cornflakes','knuspermüsli','overnight oats',
      'linsen','rote linsen','grüne linsen','berglinsen','belugalinsen','bohnen','kidneybohnen',
      'weiße bohnen','schwarze bohnen','borlotti','kichererbsen','spalterbsen','mungobohnen',
      'edamame trocken',
      'hefe','trockenhefe','frischhefe','backpulver','natron','backsoda','weinstein',
      'johannisbrotkernmehl','pfeilwurzstärke','speisestärke','maisstärke','stärke',
      'backkakao','kakaopulver','schokotropfen','schokostücke','kuvertüre','zartbitter-kuvertüre',
      'backoblaten','marzipan','rosinen','sultaninen','datteln','getrocknete feigen',
      'getrocknete aprikosen','trockenobst',
      'brotmischung','pizzateig','pizzateigmischung','fertigteig','mürbeteig','blätterteig-mix',
    ],
  },
  {
    id: 'canned',
    name: 'Konserven & Saucen',
    emoji: '🥫',
    keywords: [
      'dose','dosen','dosentomaten','stückige tomaten','gehackte tomaten','passierte tomaten',
      'passata','tomatenmark','tomatensauce','tomatensoße','pastasauce','pastasoße',
      'bolognesesauce','bolognese','arrabbiata','carbonara-sauce','pesto','pesto rosso',
      'pesto verde','pesto basilikum','käsesoße','currysauce','currysoße',
      'ketchup','curryketchup','senf','mittelscharfer senf','dijonsenf','süßer senf','honigsenf',
      'mayonnaise','mayo','remoulade','aioli','tatarsauce','cocktailsauce','steakhouse',
      'sweet chili','süß-sauer-sauce','teriyakisauce','hoisinsauce','austernsauce',
      'barbecue','bbq-sauce','guacamole','salsa','salsa roja','salsa verde',
      'gurken','gewürzgurken','cornichons','senfgurken','silberzwiebeln','oliven-glas','oliven',
      'kapern','jalapeños','sardellen-glas','thunfisch-dose','thunfisch im wasser','thunfisch in öl',
      'mais','maisdose','zuckermais','kidneybohnen-dose','weiße bohnen-dose','bohnen-dose',
      'erbsen-dose','karotten-dose','linsen-dose','kichererbsen-dose','pilze-dose',
      'apfelmus','apfelkompott','fruchtmus','marmelade','konfitüre','gelee','fruchtaufstrich',
      'honig','waldhonig','blütenhonig','akazienhonig','honigwaben',
      'nussmus','erdnussbutter','erdnussmus','mandelmus','cashewmus','haselnussmus',
      'nutella','nuss-nougat','schoko-aufstrich','nocciolata',
      'chutney','relish','zaziki','tsatsiki','hummus-glas','baba ghanoush',
      'kokosmilch-dose','kokoscreme-dose',
    ],
  },
  {
    id: 'spices',
    name: 'Gewürze & Öl',
    emoji: '🌶️',
    keywords: [
      'salz','meersalz','steinsalz','himalaya','fleur de sel','pfeffer','schwarzer pfeffer',
      'weißer pfeffer','bunter pfeffer','cayennepfeffer','chilipulver','chili','chiliflocken',
      'paprikapulver','paprika edelsüß','rosenscharf','geräuchertes paprika','smoked paprika',
      'kreuzkümmel','kumin','koriander gemahlen','kardamom','zimt','zimtstange','nelken',
      'muskat','muskatnuss','piment','ingwerpulver','kurkuma','curcuma','curry','currypulver',
      'currypaste','garam masala','ras el hanout','dukkah','zaatar','szechuanpfeffer',
      'lorbeerblatt','lorbeer','oregano','thymian','rosmarin','majoran','bohnenkraut',
      'estragon','salbei','wacholderbeeren','fenchelsamen','anis','sternanis','vanille',
      'vanilleschote','vanilleextrakt','rosenwasser','orangenblütenwasser',
      'italienische kräuter','kräuter der provence','gewürzmischung','grillgewürz','rub',
      'bouillon','brühe','gemüsebrühe','hühnerbrühe','rinderbrühe','brühwürfel','bouillon-pulver',
      'miso','miso paste','dashi','hefeflocken','nährhefe',
      'olivenöl','natives olivenöl','rapsöl','sonnenblumenöl','kokosöl','kokosfett','palmfett',
      'erdnussöl','sesamöl','leinöl','walnussöl','traubenkernöl','butterschmalz','ghee',
      'essig','balsamico','balsamico-essig','weißer balsamico','apfelessig','weinessig',
      'reisessig','himbeeressig',
      'sojasauce','sojasoße','tamari','shoyu','fischsauce','worcestersauce','worcester',
      'tabasco','sriracha','harissa','gochujang','sambal oelek',
    ],
  },
  {
    id: 'drinks',
    name: 'Getränke',
    emoji: '🥤',
    keywords: [
      'wasser','mineralwasser','sprudel','medium','still','stilles wasser','sprudelwasser',
      'tafelwasser','tonic','tonic water','ginger ale','bitter lemon',
      'saft','fruchtsaft','orangensaft','apfelsaft','multivitamin','multi','traubensaft',
      'direktsaft','nektar','schorle','apfelschorle','johannisbeersaft',
      'limo','limonade','cola','cola zero','pepsi','fanta','sprite','spezi','mezzo mix',
      'bionade','fritz','afri cola','club mate','mate','eistee','icetea','arizona',
      'bier','pils','pilsner','helles','weißbier','weizen','kölsch','lager','ipa','radler',
      'alkoholfrei','alkoholfreies bier','malzbier',
      'wein','rotwein','weißwein','rosé','roséwein','dornfelder','riesling','grauburgunder',
      'spätburgunder','chardonnay','sauvignon','merlot','cabernet','chianti','prosecco','cava',
      'champagner','sekt','crémant','winzersekt','schorle-wein',
      'kaffee','kaffeebohnen','espressobohnen','espressopulver','filterkaffee','gemahlener kaffee',
      'löslicher kaffee','instant kaffee','kapseln','nespresso','tassimo','senseo','pads',
      'tee','schwarztee','earl grey','english breakfast','grüntee','sencha','matcha',
      'kräutertee','früchtetee','kamillentee','pfefferminztee','rooibos','chai','ingwertee',
      'glühwein','punsch','cocktail','sirup','grenadine','holunderblütensirup',
    ],
  },
  {
    id: 'snacks',
    name: 'Snacks & Süßes',
    emoji: '🍫',
    keywords: [
      'schokolade','schoko','schokoladentafel','zartbitter','milchschokolade','weiße schokolade',
      'vollmilchschokolade','ritter sport','lindt','milka','kinder schokolade','merci',
      'pralinen','praline','trüffel','rocher','mozartkugeln',
      'riegel','schokoriegel','müsliriegel','proteinriegel','fitness-riegel','mars','snickers',
      'bounty','twix','kitkat','hanuta','duplo','raffaello','toffifee','schogetten',
      'kekse','biskuits','cookies','butterkekse','doppelkeks','oreo','leibniz','prinzen',
      'hobbits','spekulatius','lebkuchen','pfeffernüsse','lebkuchenherz','printen',
      'chips','kartoffelchips','tortilla chips','tortillas-chips','nachos','popcorn',
      'flips','erdnussflips','salzstangen','saltletts','brezeln-snack','cracker','käsecracker',
      'nüsse','erdnüsse','mandeln','cashewkerne','cashews','walnüsse','haselnüsse','pistazien',
      'paranüsse','pekannüsse','macadamia','studentenfutter','nussmischung',
      'gummibärchen','haribo','fruchtgummi','lakritz','lakritze','bonbon','bonbons','lolli',
      'lutscher','werthers','halls','mentos','tic tac','kaugummi','kaugummis',
      'eis am stiel','magnum-snack','kinder maxi king','kinder bueno','kinder country',
      'dragee','m&m','smarties','milchschnitte',
    ],
  },
];

export const DEFAULT_CATEGORY = 'Konserven & Saucen';

export function detectCategory(name) {
  if (!name) return DEFAULT_CATEGORY;
  const lower = name.toLowerCase().trim();
  for (const cat of CATEGORIES) {
    if (cat.keywords.some((kw) => lower.includes(kw))) return cat.name;
  }
  return DEFAULT_CATEGORY;
}
