// Locations for the misc shopping list ("Sonstiges").
// Keywords enable auto-detection on item add — no manual dropdown needed.
// Matches are case-insensitive substring matches on the item name.

export const MISC_LOCATIONS = [
  {
    id: 'apotheke',
    name: 'Apotheke',
    emoji: '💊',
    color: '#ef4444',
    keywords: [
      'paracetamol','ibuprofen','aspirin','novalgin','ass','thomapyrin','grippostad',
      'dolormin','nurofen','voltaren','voltaren-schmerzgel',
      'nasenspray','nasentropfen','ohrentropfen','augentropfen','hustensaft','hustenlöser',
      'hustenbonbon','hustenreiz','halstabletten','lutschtabletten','neoangin',
      'pflaster','verband','mullbinde','wundschnellverband','wundsalbe','bepanthen',
      'desinfektion','desinfektionsmittel','octenisept','sterillium','fieberthermometer',
      'vitamin','vitamine','vitamin d','vitamin c','vitamin b','magnesium','zink','eisen',
      'folsäure','omega 3','probiotika','mineralstoffe','nahrungsergänzung',
      'medikament','medikamente','tabletten','kapseln','tropfen','salbe','creme-apotheke',
      'rezept','kassenrezept','privatrezept','ohrstöpsel','kompressen','fieberthermometer',
      'teststreifen','schnelltest','corona-test','selbsttest','schwangerschaftstest',
      'schlafmittel','beruhigungstee','baldrian','melatonin',
    ],
  },
  {
    id: 'baumarkt',
    name: 'Baumarkt',
    emoji: '🔨',
    color: '#f97316',
    keywords: [
      'schraube','schrauben','holzschraube','spax','senkkopfschraube','muttern','mutter',
      'unterlegscheibe','unterlegscheiben','nagel','nägel','tacker','tackernadeln',
      'dübel','gipskartondübel','bohrer','spiralbohrer','steinbohrer','holzbohrer',
      'säge','stichsäge','handsäge','sägeblatt','sägeblätter',
      'hammer','zange','kneifzange','rohrzange','wasserpumpenzange','kombizange','seitenschneider',
      'schraubendreher','schraubenzieher','kreuzschlitz','schlitz','torx','innensechskant',
      'inbus','inbusschlüssel','ringschlüssel','maulschlüssel','schraubenschlüssel',
      'akkuschrauber','bohrmaschine','akkuschrauber-akku','akku-ladegerät',
      'farbe','wandfarbe','dispersionsfarbe','lack','lasur','holzlasur','grundierung','primer',
      'pinsel','farbrolle','farbwanne','abdeckfolie','malerkrepp','kreppband',
      'silikon','acryl','fugenmasse','dichtmittel','dichtungsband','montagekleber',
      'sekundenkleber','holzleim','uhu','kleber-baumarkt','ponal',
      'schmirgelpapier','schleifpapier','schleifblock',
      'holz','holzplatte','holzlatte','kantholz','osb-platte','mdf-platte','sperrholz',
      'leiste','bauholz','brett','bretter',
      'kabel-baumarkt','rohr','abflussrohr','hahn','wasserhahn','duschkopf','duschschlauch',
      'gartenschlauch','gießkanne','blumenerde','pflanzerde','erde','dünger','samen',
      'saatgut','rankgitter','gartenhandschuhe','spaten','schaufel','harke','rechen',
    ],
  },
  {
    id: 'hygiene',
    name: 'Hygieneartikel',
    emoji: '🧴',
    color: '#a855f7',
    keywords: [
      'shampoo','spülung','conditioner','haarspülung','haarkur','trockenshampoo','haarspray',
      'haarwachs','haargel','stylingcreme','haaröl','haarfarbe','colorationscreme',
      'duschgel','duschcreme','seife','flüssigseife','kernseife','handseife','naturseife',
      'bodylotion','körperlotion','körpermilch','bodybutter','handcreme','fußcreme',
      'gesichtscreme','tagescreme','nachtcreme','gesichtsreinigung','reinigungsmilch',
      'gesichtswasser','toner','mizellenwasser','peeling','gesichtsmaske','augencreme',
      'sonnencreme','sonnenmilch','sonnenspray','lsf','after sun','selbstbräuner',
      'zahnpasta','zahncreme','zahnbürste','elektrische zahnbürste','bürstenkopf',
      'zahnseide','interdentalbürste','zahnpflege','mundwasser','mundspülung','listerine',
      'deo','deospray','deoroller','deostick','antitranspirant',
      'rasierer','rasierklingen','nassrasierer','rasierschaum','rasiergel','rasierwasser',
      'aftershave','epilierer','enthaarungscreme','wachsstreifen',
      'parfum','parfüm','eau de toilette','eau de parfum','körperspray',
      'tampons','binden','slipeinlagen','menstruationstasse','periodenunterwäsche',
      'windeln','babywindeln','feuchttücher','babylotion','puder-baby','babyöl',
      'wattestäbchen','wattepads','abschminkpads','kosmetiktücher','taschentücher-drogerie',
      'nagellack','nagellackentferner','nagelfeile','nagelschere','nagelzwicker',
      'make-up','foundation','concealer','lippenstift','lipgloss','mascara','wimperntusche',
      'lidschatten','eyeliner','puder','rouge','bronzer','highlighter','primer-make-up',
      'kamm','haarbürste','rundbürste','haargummi','haarklammer','spange',
      'pinzette','lockenstab','glätteisen','fön','föhn','haartrockner',
    ],
  },
  {
    id: 'haushalt',
    name: 'Haushalt',
    emoji: '🏠',
    color: '#14b8a6',
    keywords: [
      'waschmittel','flüssigwaschmittel','waschpulver','colorwaschmittel','vollwaschmittel',
      'feinwaschmittel','wollwaschmittel','weichspüler','weichspülerkonzentrat',
      'waschkapseln','waschpods','fleckentferner','vanish','gallseife',
      'spülmittel','geschirrspülmittel','spültabs','tabs','geschirrspül','klarspüler',
      'regeneriersalz','spülmaschinensalz','maschinenreiniger','waschmaschinenreiniger',
      'reiniger','allzweckreiniger','universalreiniger','badreiniger','küchenreiniger',
      'glasreiniger','fensterreiniger','fensterputzmittel','bodenreiniger','wischmittel',
      'fliesenreiniger','fugenreiniger','kalkreiniger','entkalker','essigreiniger',
      'backofenreiniger','rohrreiniger','rohrfrei','ceranfeldreiniger','edelstahlreiniger',
      'scheuermilch','scheuerpulver','ata','meister proper','mr proper','frosch','sagrotan',
      'desinfektionsreiniger','hygienespüler',
      'schwamm','schwämme','topfschwamm','spülschwamm','scheuerschwamm','stahlwolle',
      'mikrofasertuch','putztuch','putzlappen','wischmop','mopp','bodenwischer',
      'staubwedel','wischbezug','eimer','putzeimer','besen','kehrbesen','handfeger',
      'kehrschaufel','müllbeutel','mülltüten','müllsack','gelber sack','biobeutel',
      'klopapier','toilettenpapier','küchenrolle','küchenpapier','papiertücher','zewa',
      'servietten','papierservietten',
      'backpapier','butterbrotpapier','backfolie','frischhaltefolie','alufolie','brotpapier',
      'gefrierbeutel','gefrierdosen','frischhaltedosen','tupperware','zipper-beutel',
      'briefumschlag','briefumschläge-drogerie',
      'lufterfrischer','raumspray','duftkerze','teelichter','kerzen','stumpenkerzen',
      'streichhölzer','feuerzeug',
      'batterie-haushalt','haushaltsbatterien','aa-batterie','aaa-batterie',
      'putzhandschuhe','gummihandschuhe','einweghandschuhe','latexhandschuhe',
    ],
  },
  {
    id: 'zoohandlung',
    name: 'Zoohandlung',
    emoji: '🐾',
    color: '#22c55e',
    keywords: [
      'katzenfutter','nassfutter','trockenfutter','katzennassfutter','katzentrockenfutter',
      'whiskas','felix','sheba','gourmet','royal canin','hills','animonda','leonardo',
      'katzenstreu','streu','klumpstreu','hygienestreu','silikatstreu','katzenklo-streu',
      'katzenmilch','kätzchenmilch','welpenmilch',
      'leckerli','katzen-leckerli','dreamies','snacks-tier','tier-snacks','kauartikel',
      'katzenminze','catnip','baldrian-katze',
      'katzenspielzeug','spielmaus','federwedel','spielangel','ball-katze','kratzball',
      'kratzbaum','kratzpappe','kratzmatte',
      'kratzsäule','katzenbett','katzenhöhle','kuschelrolle',
      'katzentoilette','streuschaufel','katzenklo','katzenklo-liner','klo-liner',
      'fellpflege','katzenbürste','kamm-katze','zeckenzange','flohshampoo','floh',
      'zeckenschutz','frontline','zecken','wurmkur-katze','antiparasitika',
      'transportbox-katze','tragebox-katze','halsband-katze','leine-katze',
      'wassernapf','futternapf','napf','trinkbrunnen',
      'aquarium','fischfutter','aquariumreiniger','wasserpflege',
    ],
  },
  {
    id: 'kleidung',
    name: 'Kleidung',
    emoji: '👕',
    color: '#0ea5e9',
    keywords: [
      't-shirt','tshirt','shirt','poloshirt','tanktop','top','bluse','hemd','leinenhemd',
      'pullover','pulli','sweatshirt','hoodie','strickjacke','cardigan','weste','pulli-dick',
      'hose','jeans','chino','stoffhose','leggings','jogginghose','sporthose','shorts',
      'kurze hose','bermuda','unterhose','slip','boxershorts','unterwäsche','bh',
      'sport-bh','nachthemd','pyjama','schlafanzug','bademantel',
      'socken','strümpfe','wollsocken','tennissocken','sneakersocken','stützstrümpfe',
      'strumpfhose','feinstrumpfhose',
      'rock','minirock','kleid','sommerkleid','abendkleid','maxikleid','cocktailkleid',
      'jacke','jeansjacke','übergangsjacke','winterjacke','daunenjacke','regenjacke','parka',
      'mantel','wintermantel','wollmantel','trenchcoat','windbreaker',
      'schuhe','sneaker','turnschuhe','laufschuhe','sportschuhe','wanderschuhe','stiefel',
      'stiefeletten','halbschuhe','loafer','ballerinas','sandalen','flipflops','badelatschen',
      'gummistiefel','high heels','pumps','boots',
      'mütze','beanie','basecap','cap','stirnband','sonnenhut','strohhut','wollmütze',
      'schal','loop-schal','tuch','halstuch','seidentuch',
      'handschuhe','fingerhandschuhe','fäustlinge','lederhandschuhe','wollhandschuhe',
      'gürtel','hosenträger','krawatte','fliege','einstecktuch',
      'tasche','handtasche','umhängetasche','shopper','rucksack','schulrucksack',
      'sportbeutel','turnbeutel',
    ],
  },
  {
    id: 'buero',
    name: 'Bücher & Büro',
    emoji: '📚',
    color: '#6366f1',
    keywords: [
      'buch','bücher','roman','krimi','fachbuch','sachbuch','kinderbuch','bilderbuch',
      'kochbuch','reiseführer','biografie','taschenbuch','hardcover','hörbuch',
      'zeitschrift','magazin','zeitung','comic','manga',
      'stift','stifte','kugelschreiber','kuli','kulis','tintenroller','fineliner','marker',
      'textmarker','leuchtmarker','filzstift','filzstifte','buntstift','buntstifte','wachsmalstift',
      'bleistift','bleistifte','druckbleistift','radiergummi','radierer','anspitzer','spitzer',
      'füller','tintenpatrone','tintenpatronen','tinte','tintenroller',
      'heft','hefte','schulheft','collegeblock','notizblock','notizbuch','journal',
      'spiralblock','ringbuch','ordner','aktenordner','leitz-ordner','register','trennblätter',
      'hefter','schnellhefter','klarsichthülle','klarsichthüllen','prospekthüllen','dokumentenhülle',
      'papier','druckerpapier','kopierpapier','a4-papier','fotopapier','kartonpapier','tonpapier',
      'briefpapier','umschlag','briefumschlag','briefumschläge','versandtasche','luftpolstertasche',
      'post-it','klebezettel','haftnotiz','notizzettel','karteikarten','lernkarten',
      'toner','druckertoner','druckerpatrone','tintenstrahlpatrone','druckerkartusche',
      'drucker-tinte',
      'schere','büroschere','bastelschere','cutter','teppichmesser','locher','tacker-büro',
      'tacker','tackerklammern','heftklammern','briefklammern','büroklammern','gummiband','gummibänder',
      'klebeband','tesa','klebestift','klebepistole','bastelkleber','sekundenkleber-büro',
      'lineal','geodreieck','zirkel','mathezubehör',
      'kalender','tischkalender','wandkalender','taschenkalender','planer','terminplaner',
      'to-do-block','notizbuch-moleskine','moleskine','leuchtturm',
    ],
  },
  {
    id: 'elektro',
    name: 'Elektro & Technik',
    emoji: '🔌',
    color: '#eab308',
    keywords: [
      'kabel','hdmi','hdmi-kabel','usb-kabel','usb-c-kabel','usb-c','lightning-kabel','lightning',
      'micro-usb','audiokabel','klinkenkabel','aux-kabel','netzwerkkabel','lan-kabel','patchkabel',
      'verlängerungskabel','stromkabel','ladekabel',
      'ladegerät','schnellladegerät','netzteil','usb-netzteil','usb-adapter','stecker','eu-stecker',
      'reisestecker','reiseadapter','steckdose','steckdosenleiste','mehrfachsteckdose','verteiler',
      'überspannungsschutz','zeitschaltuhr','funksteckdose','smart plug',
      'batterie','batterien','aa','aaa','aa-akku','aaa-akku','akku','ladegerät-batterien',
      'c-batterie','d-batterie','9-volt','knopfzelle','cr2032','cr2025','cr2016',
      'powerbank','laptop-akku','handy-akku','notebook-akku',
      'glühbirne','led','led-lampe','leuchtmittel','energiesparlampe','deckenleuchte','lampe',
      'leselampe','schreibtischlampe','nachttischlampe','stehlampe','wandlampe',
      'e27','e14','gu10','fassung-lampe',
      'usb-stick','festplatte','externe festplatte','ssd','speicherkarte','sd-karte','micro-sd',
      'cd-rom','dvd-rohling','cd-rohling',
      'kopfhörer','in-ear','over-ear','bluetooth-kopfhörer','airpods','earpods','earbuds',
      'lautsprecher','bluetooth-lautsprecher','bluetooth-box','sounddock','boombox',
      'maus-pc','funkmaus','bluetooth-maus','tastatur-pc','funktastatur','bluetooth-tastatur',
      'mauspad','laptop-tasche','laptop-sleeve','notebook-tasche',
      'webcam','headset','mikrofon','streaming-mikrofon',
      'monitor','bildschirm','fernseher','hdmi-splitter','hdmi-adapter',
      'handyhülle','handy-hülle','schutzfolie','display-schutz','panzerglas','displayschutzfolie',
      'handy-halter','kfz-halter','auto-ladegerät',
      'fernbedienung','tv-fernbedienung','batterie-knopfzelle',
    ],
  },
  {
    id: 'geschenke',
    name: 'Geschenke',
    emoji: '🎁',
    color: '#ec4899',
    keywords: [
      'geschenk','geschenke','geburtstagsgeschenk','weihnachtsgeschenk','hochzeitsgeschenk',
      'gastgeschenk','mitbringsel','wichtelgeschenk','geldgeschenk',
      'geschenkpapier','geschenkband','schleife','geschenkanhänger','geschenkbox',
      'präsentkorb','geschenkkorb','geschenktasche','geschenkbeutel',
      'grußkarte','geburtstagskarte','weihnachtskarte','hochzeitskarte','trauerkarte',
      'glückwunschkarte','karte-glückwunsch',
      'deko','dekoration','kerze-geschenk','duftkerze-geschenk',
      'blumenstrauß','blumen','strauß','schnittblumen','rose','rosen','tulpen',
      'gutschein','gutscheinkarte','geldbeutel-geschenk','schmuckstück',
    ],
  },
  {
    id: 'sonstiges',
    name: 'Sonstiges',
    emoji: '📦',
    color: '#64748b',
    keywords: [],
  },
];

export const DEFAULT_MISC_LOCATION = 'Sonstiges';

export function detectLocation(name) {
  if (!name) return DEFAULT_MISC_LOCATION;
  const lower = name.toLowerCase().trim();
  for (const loc of MISC_LOCATIONS) {
    if (loc.keywords.some((kw) => lower.includes(kw))) return loc.name;
  }
  return DEFAULT_MISC_LOCATION;
}

export function getLocationMeta(tagName) {
  return (
    MISC_LOCATIONS.find((l) => l.name === tagName) ||
    // Fallback for legacy/custom tags
    { id: `custom-${tagName}`, name: tagName, emoji: '🏷️', color: '#64748b' }
  );
}
